apiVersion: 1

datasources:
  - name: MLPro-Postgres
    type: postgres
    uid: mlpro-postgres
    url: postgres:5432
    user: appuser
    secureJsonData:
      password: apppass
    jsonData:
      database: packages
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
